image: docker:latest
services:
    - docker:dind

variables:
    DOCKER_DRIVER: overlay
    HEROKU_APP_NAME_FRONTEND: se2-group-1
    HEROKU_APP_NAME_BACKEND: floating-escarpment-03719
    HEROKU_REGISTRY_IMAGE_FRONTEND: registry.heroku.com/${HEROKU_APP_NAME_FRONTEND}/web
    HEROKU_REGISTRY_IMAGE_BACKEND: registry.heroku.com/${HEROKU_APP_NAME_BACKEND}/web 
    CACHE_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE/${CI_PROJECT_NAME}

stages:
    - deploy

deploy-frontend:
    stage: deploy
    script:
        - apk add --no-cache curl
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker pull $CACHE_IMAGE:frontend || true
        - docker build --cache-from $CACHE_IMAGE:frontend --tag $CACHE_IMAGE:frontend --tag $HEROKU_REGISTRY_IMAGE_FRONTEND --file ./docker/food-truck-frontend.Dockerfile ./food-truck-frontend/
        - docker push $CACHE_IMAGE:frontend
        - docker login -u _ -p $HEROKU_AUTH_TOKEN registry.heroku.com
        - docker push $HEROKU_REGISTRY_IMAGE_FRONTEND
        - chmod +x ./heroku/release-frontend.sh
        - ./heroku/release-frontend.sh

deploy-backend:
    stage: deploy
    script: 
        - apk add --no-cache curl
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker pull $CACHE_IMAGE:backend || true
        - docker build --cache-from $CACHE_IMAGE:backend --tag $CACHE_IMAGE:backend --tag $HEROKU_REGISTRY_IMAGE_BACKEND --file ./docker/food-truck-api.Dockerfile ./food-truck-api/
        - docker push $CACHE_IMAGE:backend
        - docker login -u _ -p $HEROKU_AUTH_TOKEN registry.heroku.com
        - docker push $HEROKU_REGISTRY_IMAGE_BACKEND
        - chmod +x ./heroku/release-backend.sh
        - ./heroku/release-backend.sh
