image: docker:latest
services:
    - docker:dind

variables:
    DOCKER_DRIVER: overlay
    HEROKU_APP_NAME_FRONTEND: se2-group-1
    HEROKU_APP_NAME_BACKEND: floating-escarpment-03719
    HEROKU_REGISTRY_IMAGE_FRONTEND: registry.heroku.com/${HEROKU_APP_NAME_FRONTEND}/web
    HEROKU_REGISTRY_IMAGE_BACKEND: registry.heroku.com/${HEROKU_APP_NAME_BACKEND}/web 

stages:
    - deploy

deploy-frontend:
    stage: deploy
    script:
        - apk add --no-cache curl
        - docker build --tag $HEROKU_REGISTRY_IMAGE_FRONTEND --file ./docker/food-truck-frontend.Dockerfile ./food-truck-frontend/
        - docker login -u _ -p $HEROKU_AUTH_TOKEN registry.heroku.com
        - docker push $HEROKU_REGISTRY_IMAGE_FRONTEND
        - chmod +x ./heroku/release-frontend.sh
        - ./heroku/release-frontend.sh

deploy-backend:
    stage: deploy
    script: 
        - apk add --no-cache curl
        - docker build --tag $HEROKU_REGISTRY_IMAGE_BACKEND --file ./docker/food-truck-backend.Dockerfile ./food-truck-api/
        - docker login -u _ -p $HEROKU_AUTH_TOKEN registry.heroku.com
        - docker push $HEROKU_REGISTRY_IMAGE_BACKEND
        - chmod +x ./heroku/release-backend.sh
        - ./heroku/release-backend.sh
